### PR TITLE
fixed 'a' button on index motion controller

### PR DESCRIPTION
**Pull request by BuzzteeBear**
added missing /click into path

### CODE REVIEW

**Comment by mbucchia** [comment]
So I'm finally looking into this... and I think this is a runtime bug(?)

Per https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#input-suggested-bindings

>  If the path refers to the parent of input values instead of to an input value itself, the runtime must use …/example/path/click instead of …/example/path if it is available. 

This is why I put all those bindings without the `/click` suffix.

Was your issue with Varjo runtime? If so we might report the issue to them. Meanwhile we can still put the explicit leaf path - but it's a little annoying :)

**Comment by BuzzteeBear** [comment]
I was using the varjo runtime indeed. Iirc I didn't bother to check with SteamVR

**Comment by mbucchia** [comment]
> I was using the varjo runtime indeed. Iirc I didn't bother to check with SteamVR

Thanks. I guess I will just need to be safe and add the explicit leaf atom for all of them... I will probably just do that all at once and decline/close this PR.

Thanks for reporting your findings!

**Comment by BuzzteeBear** [comment]
That's fine for me

**Pull request closed without merging**
